### ISSUE TITLE
Problem with embedding

### ISSUE THREAD

**Issue by vinerya** [martinez-zacharya/TRILL#11]
running 'embed' got me this:
`Traceback (most recent call last):
  File "/usr/local/bin/trill", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/trill/trill_main.py", line 394, in cli
    main(args)
  File "/usr/local/lib/python3.8/dist-packages/trill/trill_main.py", line 273, in main
    model = ESM(eval(model_import_name), float(args.lr), args.LEGGO)
AttributeError: 'Namespace' object has no attribute 'lr'`

**Comment by martinez-zacharya** [comment]
Can you post the exact command you used for the error?

**Comment by vinerya** [comment]
`trill example_2 1 embed mydata.fasta`

**Comment by martinez-zacharya** [comment]
Ok, the issue should be fixed! Sorry, TRILL is going to be under pretty heavy development for the next few weeks as it gets closer to v1.0.0
