### ISSUE TITLE
Support planned for ProGen model?

### ISSUE THREAD

**Issue by amorehead** [martinez-zacharya/TRILL#24]
Hello. Thank you for putting together this great resource. Are there any plans in place for integrating the ProGen model within this repository in the near future?

Reference: https://www.nature.com/articles/s41587-022-01618-2

**Comment by martinez-zacharya** [comment]
Thanks for your interest! Integrating ProGen2 is definitely on my to-do list for the near future. Should be within the next few weeks 👍
