### ISSUE TITLE
Cannot access Colab instructions

### ISSUE THREAD

**Issue by spleonard1** [martinez-zacharya/TRILL#31]
Hi! Looking to play around with trill on colab- the link to the notebook with install instructions from the online documentation appears to have the wrong permissions or not be functional- I can not access it. 

https://colab.research.google.com/drive/1mx16cDAEgCYtflKm80mE8L_ZEk7Upxxe#scrollTo=AunNpGWa8tGn

Thanks!

**Comment by martinez-zacharya** [comment]
Hey Sean! Can you send me a screenshot of what page the link pulls up for you? I've checked the permissions and it seems that anyone with the link should be able to view, but maybe it's a different notebook.

**Comment by martinez-zacharya** [comment]
Hey Sean! Can you send me a screenshot of what page the link pulls up for you? I've checked the permissions and it seems like anyone with the URL should be able to open it, but maybe I'm using a different notebook.

**Comment by spleonard1** [comment]
Oops! Sorry, I let this languish. I just rechecked and it seems I can access the notebook just fine. I'll go ahead and close the issue if I can. Thanks!!

**Comment by spleonard1** [comment]
Hey! I can access the colab instructions fine, but the install isn't working. Something to do with cudatoolkit. Trying to install by running through cells on a GPU (T4) colab runtime. Several of the mamba commands give the same ultimate error about not finding cudatoolkit 12.2.*.


No package can be installed for pin: cudatoolkit 12.2.*

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 547, in install
        solver.add_pin(final_spec)
    RuntimeError: No package can be installed for pin: cudatoolkit 12.2.*

`$ /usr/local/bin/mamba install -c conda-forge openmm swig pdbfixer openbabel smina fpocket vina`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
               CONDA_ROOT=/usr/local
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/lib:/usr/lib64-nvidia
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : /usr/local/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __glibc=2.35=0
                          __linux=6.1.58=0
                          __unix=0=0
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/6.1.58+ ubuntu/22.04.3 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
####################################

If I try to run trill anyway, I get this error: 
Traceback (most recent call last):
  File "/usr/local/bin/trill", line 5, in <module>
    from trill.trill_main import cli
  File "/usr/local/lib/python3.10/site-packages/trill/trill_main.py", line 30, in <module>
    from trill.utils.lightning_models import ESM, ProtGPT2, CustomWriter, ESM_Gibbs, ProtT5, ZymCTRL, ProstT5, Custom3DiDataset, Ankh
  File "/usr/local/lib/python3.10/site-packages/trill/utils/lightning_models.py", line 23, in <module>
    from esm.inverse_folding.multichain_util import sample_sequence_in_complex
  File "/usr/local/lib/python3.10/site-packages/esm/inverse_folding/__init__.py", line 6, in <module>
    from . import gvp_transformer
  File "/usr/local/lib/python3.10/site-packages/esm/inverse_folding/gvp_transformer.py", line 16, in <module>
    from .features import DihedralFeatures
  File "/usr/local/lib/python3.10/site-packages/esm/inverse_folding/features.py", line 73, in <module>
    from .gvp_modules import GVP, LayerNorm
  File "/usr/local/lib/python3.10/site-packages/esm/inverse_folding/gvp_modules.py", line 33, in <module>
    from torch_geometric.nn import MessagePassing
ModuleNotFoundError: No module named 'torch_geometric'


Thanks!

**Comment by martinez-zacharya** [comment]
Thanks for documenting the error so thoroughly! Try using this notebook, I just patched TRILL to work with colab again https://colab.research.google.com/drive/1UK5ULlFAmcjteabgXsfjizqFF35jJlAz#scrollTo=m46pBfehKJv0
