### ISSUE TITLE
Format of the key file for visualize

### ISSUE THREAD

**Issue by amin-sagar** [martinez-zacharya/TRILL#45]
Hello.
Thanks for this awesome work.
I am trying to embed a bunch of protein families using ESM2 and visualize using UMAP to see if the the families are in distinct clusters. 
I found in the documentation
```
--key
Input a CSV, with your group mappings for your embeddings where the first column is the label and the second column is the group to be colored.
```
Can you please give a small example of the format of the file?
For example, let say I just have one sequence of a polymerase and one sequence of a kinase, and I want to show the two as different colors, what would the csv file look like?

I would be really grateful for your help.
Best,
Amin.

**Comment by martinez-zacharya** [comment]
Sorry for the delay! Below is an example of a key file. Note that while Class can be any arbitrary string, the Label column must match the header in the input fasta file.

> Label,Class
> P63086,Cell membrane
> O75439,Mitochondrion
> Q2TBK2,Mitochondrion
> O35094,Membrane
> Q4QQW3,Mitochondrion
> Q32PI5,Cytoplasm
> Q60415,Membrane

Also, you can use the utils command to help create your key for you! Below is an example of passing an absolute path to a directory where your fasta files are, separated into classes. For instance, if you had 4 fasta files in the directory, it would output a key where there are 4 classes. 

`trill key_example 0 utils prepare_class_key --dir /path/to/fasta/files/sep/by/class`

You can also pass a text file with `--fasta_paths_txt` where each line has an absolute path to a fasta file. Each fasta file (and all of the associated sequences) will be considered its own class.

`trill key_example 0 utils prepare_class_key --fasta_paths_txt /path/to/file/paths.txt`

Here is an example of how the paths.txt could look if you only had two classes-

> /path/to/file/seqs1.fasta
> /path/to/other/file/seqs2.fasta

**Comment by amin-sagar** [comment]
Thanks @martinez-zacharya 
This is exactly what I was looking for.
Best,
Amin.
